FROM python:3.11

RUN apt-get update && apt-get upgrade -y && apt-get install -y chromium-driver

RUN pip install poetry

WORKDIR /usr/src/vectorstore_updater_app

COPY pyproject.toml poetry.lock ./

RUN poetry install

COPY . /usr/src/vectorstore_updater_app/

# Run Uvicorn server
ENTRYPOINT ["uvicorn", "vs_main:vectorstore_updater_app", "--proxy-headers", "--host", "0.0.0.0"]