FROM python:3.11

RUN apt-get update && apt-get upgrade -y && apt-get install -y chromium-driver

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /usr/src/vectorstore_updater_app

COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock

RUN poetry install --no-root

COPY . /usr/src/vectorstore_updater_app/

# Expose the port that Uvicorn will run on
EXPOSE 8000

# Run Uvicorn server
CMD ["poetry", "run", "/usr/local/bin/uvicorn", "vs_main:vectorstore_updater_app", "--proxy-headers", "--host", "0.0.0.0"]