FROM python:3.11.0

RUN apt-get update && apt-get upgrade -y && apt-get install -y chromium-driver

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"

WORKDIR /usr/src/vectorstore_updater_app

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

COPY . /usr/src/vectorstore_updater_app/