FROM python:3.11

RUN apt-get update && apt-get upgrade -y && apt-get install -y chromium-driver

RUN pip install poetry

WORKDIR /usr/src/vectorstore_updater_app

COPY pyproject.toml poetry.lock ./

RUN poetry install
RUN poetry shell

ENV VIRTUAL_ENV=/usr/src/vectorstore_updater_app/.venv \
    PATH="/usr/src/vectorstore_updater_app/.venv/bin:$PATH"

COPY . /usr/src/vectorstore_updater_app/