"""Auto-generated migration for dev

Revision ID: b485c16febf3
Revises: 7a2958fc579c
Create Date: 2024-06-28 11:23:52.729820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b485c16febf3'
down_revision: Union[str, None] = '7a2958fc579c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
